#!/bin/sh
#info: Configure and enable SSHD, requires Cygwin, run this inside Windows XP
# based on: https://cygwin.com/pipermail/cygwin/2006-June/147909.html
# https://web.archive.org/web/20060603194000/http://pigtail.net/LRP/printsrv/cygwin-sshd.html

cd / || exit 1

# add cygwin to environment PATH
REG_ENV="\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment"
regtool set "$REG_ENV\Path" "%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;C:\posix\bin" || exit 1

# use UNIX-like permission structure via ntsec
# info: https://web.archive.org/web/20060702075256/http://pigtail.net/LRP/printsrv/ntsec.html
regtool set "$REG_ENV\CYGWIN" "ntsec" || exit 1

# convert Windows users to POSIX users
mkpasswd --local >/etc/passwd || exit 1
mkgroup --local >/etc/group || exit 1

# configure and enable SSHD
cygrunsrv --stop sshd
cygrunsrv --remove sshd
ssh-host-config -y
cygrunsrv --start sshd || exit 1

# open port 22
netsh firewall add portopening TCP 22 "TCP Port 22"

# clean up logs
echo "" >/var/log/lastlog
echo "" >/var/log/sshd.log
rm -f /home/Administrator/.bash_history
